# Generated by Django 3.2.5 on 2021-07-14 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('user',)},
        ),
    ]
